name: zebrautil
description: A plugin for working with zebra printers in flutter
version: 1.5.0
repository: https://github.com/shashwatxx/zebra_printer_utility


environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
