name: zebrautil
description: A plugin for working with zebra printers in flutter
version: 1.5.3
repository: https://github.com/shashwatxx/zebra_printer_utility

publish_to: https://onepub.dev/api/kjhxxpsdav/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.1
  flutter_lints: ^6.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
